services:
  app:
    build: .
    container_name: geois-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - memcached
      - gearman
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: geois-mysql
    volumes:
      - ../mysql-data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --skip-grant-tables --skip-networking=0
    restart: unless-stopped

  memcached:
    image: memcached:1.6-alpine
    container_name: geois-memcached
    restart: unless-stopped

  gearman:
    image: artefactual/gearmand
    container_name: geois-gearman
    ports:
      - "4730:4730"
    restart: unless-stopped

  worker:
    build: .
    container_name: geois-worker
    command: php /var/www/html/index.php worker listen
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - gearman
      - memcached
    restart: unless-stopped
